services:
  frontend:
    volumes:
      - frontend_vol:/src/frontend
    build:
      context: ./services/frontend
  backend:
    volumes:
      - backend_vol:/src/backend
    build:
      context: ./services/backend

volumes:
  frontend_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${FRONTEND_SRC}
  backend_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${BACKEND_SRC}