services:
  frontend:
    ports:
      - 5173:5173
    stdin_open: true
    tty: true   
    volumes:
        - "${FRONTEND_SRC}:/node/app:delegated"
    build:
      context: ./services/frontend
    networks:
      frontend:

  backend:
    stdin_open: true
    tty: true 
    volumes:
      - "${BACKEND_SRC}:/node/app:delegated"
    build:
      context: ./services/backend
    networks:
      frontend:

  database:
    ports:
      - 5432:5432
    stdin_open: true
    tty: true
    build:
      context: ./services/database
      args:
        - DB_NAME=${DB_NAME}
        - DB_USERNAME=${DB_USERNAME}
        - DB_USERPWD=${DB_USERPWD}
    networks:
      backend:

networks:
  frontend:
  backend:
