services:
  frontend:
    ports:
      - ${FRONTEND_PORT}:5173
    stdin_open: true
    tty: true
    volumes:
        - "${FRONTEND_SRC}:/node/app:delegated"
    build:
      target: starter
      context: ./services/frontend

  backend:
    ports:
      - 3000:3000
    stdin_open: true
    tty: true 
    volumes:
      - "${BACKEND_SRC}:/node/app:delegated"
    build:
      target: starter
      context: ./services/backend
    networks:
      backend:

  database:
    ports:
      - 5432:5432
    stdin_open: true
    tty: true
    build:
      target: starter
      context: ./services/database
      args:
        - DB_NAME=${DB_NAME}
        - DB_USERNAME=${DB_USERNAME}
        - DB_USERPWD=${DB_USERPWD}
    networks:
      backend:
        aliases:
          - postgresql

networks:
  backend:
